### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by navierula** [droopzilla/sql-scratch-capstone-turn-in#1]
**Report (4/4)**
Every answer includes text and query results (as supporting evidence). Related queries are uploaded in a separate .sql file. Conclusions are clearly stated and based on evidence.

**Query Accuracy (4/4)**
All queries accurately retrieve the data intended (as stated or implied by comments or the presentation).

**Query Formatting (4/4)**
Queries are formatted appropriately according to general style guides.

**Understanding Underlying Concepts and Terminology (4/4)**
Report demonstrates clear understanding of connections between UTM parameters, marketing touchpoints, and touch attribution. Terms are used correctly throughout the report.

---

Great job on this project! You did an excellent job with your queries. I appreciated that your provided comments for each one. Your slides were also well done, including evidence of both queries and query results.

**Comment by droopzilla** [comment]
Thank you for the feedback!
